language: python

# use container-based infrastructure
sudo : false
dist: trusty

python:
  - "2.7"
  - "3.5"
  - "3.6"

# Setup miniconda
before_install:
    - MINICONDA_URL="http://repo.continuum.io/miniconda"
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        MINICONDA_FILE=Miniconda3-latest-Linux-x86_64.sh
        CONDA_PREFIX=/home/travis/miniconda3;
      else
        MINICONDA_FILE=Miniconda3-latest-MacOSX-x86_64.sh
        CONDA_PREFIX=/Users/travis/miniconda3;
      fi;
    - wget $MINICONDA_URL/$MINICONDA_FILE -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$CONDA_PREFIX/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda update --yes --quiet conda
    # Install dependencies
    - conda install python=$TRAVIS_PYTHON_VERSION pip
    - conda install conda-build
    - conda install anaconda-client
    # Show installed pkg information for postmortem diagnostic
    - conda list

# install packages
install:
  - deps='numpy matplotlib scipy pytest'
  - conda create -n apsg $deps python=$TRAVIS_PYTHON_VERSION
  - source activate apsg
  - conda build --python $TRAVIS_PYTHON_VERSION conda-build/apsg
  - conda install apsg --use-local --no-deps

script:
#  - python -m unittest discover -v
  - python -m pytest -v

after_success:
  - chmod +x ci/deploy_anaconda.sh

deploy:
 # Deploy to Anaconda.org
  - provider: script
    script: ci/deploy_anaconda.sh
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = 3.5

notifications:
  email:
    - lexa.ondrej@gmail.com

