{% set data = load_setup_py_data() %}

package:
  name: apsg
  version: {{ data.version }}

source:
  git_url: https://github.com/ondrolexa/apsg.git
  git_rev: {{ data.version }}

build:
  noarch: python
  entry_points:
    - iapsg=apsg.shell:main
  script: python setup.py install

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy >=x.x
    - matplotlib >=2.2.3
    - scipy

  run:
    - python {{ python }}
    - numpy >=x.x
    - matplotlib
    - scipy

test:
  # Python imports
  imports:
    - apsg
    - apsg.core
    - apsg.plotting
    - apsg.db
    - apsg.helpers
    - apsg.tensors
    - apsg.shell

about:
  home: http://ondrolexa.github.io/apsg
  license: MIT License
  summary: 'APSG - structural geology module for Python'
  license_family: MIT
  doc_url: https://apsg.readthedocs.org
  dev_url: https://github.com/ondrolexa/apsg

extra:
  maintainers:
   - Ondrej Lexa <lexa.ondrej@gmail.com>
